#187 Adding FIS to the EMR Workshop
awslabs/ec2-spot-workshops pull request #188
Opened 2022-04-06 16:51 UTC by christianhxc

*Issue #187*

**Description of changes:** Include the section to use FIS and trigger a Spot interruption in the EMR Workshop.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-04-20 21:49 UTC, nadaahm commented on content/running_spark_apps_with_emr_on_spot_instances/spot_interruption_experiment.md
> +* You can configure how many instances you want to interrupt with the `InstancesToInterrupt` parameter. By default, it's going to interrupt **three** instances.
instead of saying "By default" you can say "For this lab or in this template"

2022-04-20 21:50 UTC, nadaahm commented on content/running_spark_apps_with_emr_on_spot_instances/spot_interruption_experiment.md
> +* You can configure how many instances you want to interrupt with the `InstancesToInterrupt` parameter. By default, it's going to interrupt **three** instances.
you may something like, you can interrupt up to 5 instances in a FIS template

2022-04-20 21:57 UTC, nadaahm commented on content/running_spark_apps_with_emr_on_spot_instances/spot_interruption_experiment.md
> +* You can also configure how much time you want the expriment to run with the `DurationBeforeInterruption` parameter. By default, it's going to take two minutes. This means that as soon as you launch
maybe explain this in different words

2022-04-20 22:03 UTC, nadaahm commented on content/running_spark_apps_with_emr_on_spot_instances/spot_interruption_experiment.md
> +Let's continue by creating the Spot interruption experiment template using Cloudformation.You can view and download the CloudFormation template (**fisspotinterruption.yaml**) from GitHub [here](https
add a wget command to download the template

2022-04-22 03:03 UTC, nadaahm requested changes

2022-04-22 03:03 UTC, nadaahm commented on content/running_spark_apps_with_emr_on_spot_instances/spot_interruption_fis.md
> +Run the following command to get an understanding of how many instances are currently before the Spot interruption:
was there a word missing here?

2022-04-22 08:49 UTC, christianhxc commented on content/running_spark_apps_with_emr_on_spot_instances/spot_interruption_experiment.md
> +sed -i -e "s#ResourceTagValue#TASK#g" -e "s#FIS_EXP_NAME#$FIS_EXP_NAME#g" fisspotinterruption.yaml
good catch, thank you!

2022-04-22 08:50 UTC, christianhxc commented on content/running_spark_apps_with_emr_on_spot_instances/spot_interruption_fis.md
> +Run the following command to get an understanding of how many instances are currently before the Spot interruption:
yes, it's "running", I'll add it

2022-04-25 13:41 UTC, nadaahm approved these changes

2022-04-25 13:41 UTC, merged